# Changes here will be overwritten by Copier
_commit: 99c49ec
_src_path: gh:34j/pypackage-template
cli_name: shift-nth-row-n-steps
copyright_year: '2024'
documentation: true
email: 34j.github@proton.me
full_name: 34j
github_username: 34j
has_cli: true
initial_commit: false
is_django_package: false
open_source_license: MIT
open_with_vscode: true
package_name: shift_nth_row_n_steps
project_name: Shift Nth Row N Steps
project_short_description: Shift Nth row N steps in NumPy / PyTorch / TensorFlow /
    JAX
project_slug: shift-nth-row-n-steps
setup_venv: false

